version: "3.9"

services:
  app:
    build: .
    container_name: ecomm-app
    restart: always
    ports:
      - 8080:8080
    networks:
      - ecomm-network

networks:
  ecomm-network:
    driver: bridge